export const ULKELER = [
  {kod:'DE',isim:'Almanya',bayrak:'🇩🇪',telKod:'+49'},
  {kod:'TR',isim:'Türkiye',bayrak:'🇹🇷',telKod:'+90'},
  {kod:'UA',isim:'Ukrayna',bayrak:'🇺🇦',telKod:'+380'},
  {kod:'RU',isim:'Rusya',bayrak:'🇷🇺',telKod:'+7'},
  {kod:'US',isim:'Amerika',bayrak:'🇺🇸',telKod:'+1'},
  {kod:'GB',isim:'İngiltere',bayrak:'🇬🇧',telKod:'+44'},
  {kod:'FR',isim:'Fransa',bayrak:'🇫🇷',telKod:'+33'},
  {kod:'IT',isim:'İtalya',bayrak:'🇮🇹',telKod:'+39'},
  {kod:'ES',isim:'İspanya',bayrak:'🇪🇸',telKod:'+34'},
  {kod:'NL',isim:'Hollanda',bayrak:'🇳🇱',telKod:'+31'},
  {kod:'BE',isim:'Belçika',bayrak:'🇧🇪',telKod:'+32'},
  {kod:'AT',isim:'Avusturya',bayrak:'🇦🇹',telKod:'+43'},
  {kod:'CH',isim:'İsviçre',bayrak:'🇨🇭',telKod:'+41'},
  {kod:'SE',isim:'İsveç',bayrak:'🇸🇪',telKod:'+46'},
  {kod:'NO',isim:'Norveç',bayrak:'🇳🇴',telKod:'+47'},
  {kod:'DK',isim:'Danimarka',bayrak:'🇩🇰',telKod:'+45'},
  {kod:'FI',isim:'Finlandiya',bayrak:'🇫🇮',telKod:'+358'},
  {kod:'IS',isim:'İzlanda',bayrak:'🇮🇸',telKod:'+354'},
  {kod:'IE',isim:'İrlanda',bayrak:'🇮🇪',telKod:'+353'},
  {kod:'PT',isim:'Portekiz',bayrak:'🇵🇹',telKod:'+351'},
  {kod:'GR',isim:'Yunanistan',bayrak:'🇬🇷',telKod:'+30'},
  {kod:'CY',isim:'Kıbrıs',bayrak:'🇨🇾',telKod:'+357'},
  {kod:'MT',isim:'Malta',bayrak:'🇲🇹',telKod:'+356'},
  {kod:'LU',isim:'Lüksemburg',bayrak:'🇱🇺',telKod:'+352'},
  {kod:'LI',isim:'Lihtenştayn',bayrak:'🇱🇮',telKod:'+423'},
  {kod:'MC',isim:'Monako',bayrak:'🇲🇨',telKod:'+377'},
  {kod:'AD',isim:'Andorra',bayrak:'🇦🇩',telKod:'+376'},
  {kod:'SM',isim:'San Marino',bayrak:'🇸🇲',telKod:'+378'},
  {kod:'VA',isim:'Vatikan',bayrak:'🇻🇦',telKod:'+379'},
  {kod:'PL',isim:'Polonya',bayrak:'🇵🇱',telKod:'+48'},
  {kod:'CZ',isim:'Çekya',bayrak:'🇨🇿',telKod:'+420'},
  {kod:'SK',isim:'Slovakya',bayrak:'🇸🇰',telKod:'+421'},
  {kod:'HU',isim:'Macaristan',bayrak:'🇭🇺',telKod:'+36'},
  {kod:'RO',isim:'Romanya',bayrak:'🇷🇴',telKod:'+40'},
  {kod:'BG',isim:'Bulgaristan',bayrak:'🇧🇬',telKod:'+359'},
  {kod:'HR',isim:'Hırvatistan',bayrak:'🇭🇷',telKod:'+385'},
  {kod:'SI',isim:'Slovenya',bayrak:'🇸🇮',telKod:'+386'},
  {kod:'BA',isim:'Bosna Hersek',bayrak:'🇧🇦',telKod:'+387'},
  {kod:'RS',isim:'Sırbistan',bayrak:'🇷🇸',telKod:'+381'},
  {kod:'ME',isim:'Karadağ',bayrak:'🇲🇪',telKod:'+382'},
  {kod:'XK',isim:'Kosova',bayrak:'🇽🇰',telKod:'+383'},
  {kod:'MK',isim:'Kuzey Makedonya',bayrak:'🇲🇰',telKod:'+389'},
  {kod:'AL',isim:'Arnavutluk',bayrak:'🇦🇱',telKod:'+355'},
  {kod:'LT',isim:'Litvanya',bayrak:'🇱🇹',telKod:'+370'},
  {kod:'LV',isim:'Letonya',bayrak:'🇱🇻',telKod:'+371'},
  {kod:'EE',isim:'Estonya',bayrak:'🇪🇪',telKod:'+372'},
  {kod:'BY',isim:'Belarus',bayrak:'🇧🇾',telKod:'+375'},
  {kod:'MD',isim:'Moldova',bayrak:'🇲🇩',telKod:'+373'},
  {kod:'KZ',isim:'Kazakistan',bayrak:'🇰🇿',telKod:'+7'},
  {kod:'UZ',isim:'Özbekistan',bayrak:'🇺🇿',telKod:'+998'},
  {kod:'TM',isim:'Türkmenistan',bayrak:'🇹🇲',telKod:'+993'},
  {kod:'KG',isim:'Kırgızistan',bayrak:'🇰🇬',telKod:'+996'},
  {kod:'TJ',isim:'Tacikistan',bayrak:'🇹🇯',telKod:'+992'},
  {kod:'GE',isim:'Gürcistan',bayrak:'🇬🇪',telKod:'+995'},
  {kod:'AM',isim:'Ermenistan',bayrak:'🇦🇲',telKod:'+374'},
  {kod:'AZ',isim:'Azerbaycan',bayrak:'🇦🇿',telKod:'+994'},
  {kod:'IR',isim:'İran',bayrak:'🇮🇷',telKod:'+98'},
  {kod:'IQ',isim:'Irak',bayrak:'🇮🇶',telKod:'+964'},
  {kod:'SY',isim:'Suriye',bayrak:'🇸🇾',telKod:'+963'},
  {kod:'LB',isim:'Lübnan',bayrak:'🇱🇧',telKod:'+961'},
  {kod:'JO',isim:'Ürdün',bayrak:'🇯🇴',telKod:'+962'},
  {kod:'IL',isim:'İsrail',bayrak:'🇮🇱',telKod:'+972'},
  {kod:'PS',isim:'Filistin',bayrak:'🇵🇸',telKod:'+970'},
  {kod:'SA',isim:'Suudi Arabistan',bayrak:'🇸🇦',telKod:'+966'},
  {kod:'AE',isim:'BAE',bayrak:'🇦🇪',telKod:'+971'},
  {kod:'QA',isim:'Katar',bayrak:'🇶🇦',telKod:'+974'},
  {kod:'KW',isim:'Kuveyt',bayrak:'🇰🇼',telKod:'+965'},
  {kod:'BH',isim:'Bahreyn',bayrak:'🇧🇭',telKod:'+973'},
  {kod:'OM',isim:'Umman',bayrak:'🇴🇲',telKod:'+968'},
  {kod:'YE',isim:'Yemen',bayrak:'🇾🇪',telKod:'+967'},
  {kod:'AF',isim:'Afganistan',bayrak:'🇦🇫',telKod:'+93'},
  {kod:'PK',isim:'Pakistan',bayrak:'🇵🇰',telKod:'+92'},
  {kod:'IN',isim:'Hindistan',bayrak:'🇮🇳',telKod:'+91'},
  {kod:'BD',isim:'Bangladeş',bayrak:'🇧🇩',telKod:'+880'},
  {kod:'LK',isim:'Sri Lanka',bayrak:'🇱🇰',telKod:'+94'},
  {kod:'MV',isim:'Maldivler',bayrak:'🇲🇻',telKod:'+960'},
  {kod:'NP',isim:'Nepal',bayrak:'🇳🇵',telKod:'+977'},
  {kod:'BT',isim:'Bhutan',bayrak:'🇧🇹',telKod:'+975'},
  {kod:'MM',isim:'Myanmar',bayrak:'🇲🇲',telKod:'+95'},
  {kod:'TH',isim:'Tayland',bayrak:'🇹🇭',telKod:'+66'},
  {kod:'LA',isim:'Laos',bayrak:'🇱🇦',telKod:'+856'},
  {kod:'KH',isim:'Kamboçya',bayrak:'🇰🇭',telKod:'+855'},
  {kod:'VN',isim:'Vietnam',bayrak:'🇻🇳',telKod:'+84'},
  {kod:'MY',isim:'Malezya',bayrak:'🇲🇾',telKod:'+60'},
  {kod:'SG',isim:'Singapur',bayrak:'🇸🇬',telKod:'+65'},
  {kod:'BN',isim:'Brunei',bayrak:'🇧🇳',telKod:'+673'},
  {kod:'ID',isim:'Endonezya',bayrak:'🇮🇩',telKod:'+62'},
  {kod:'TL',isim:'Doğu Timor',bayrak:'🇹🇱',telKod:'+670'},
  {kod:'PH',isim:'Filipinler',bayrak:'🇵🇭',telKod:'+63'},
  {kod:'CN',isim:'Çin',bayrak:'🇨🇳',telKod:'+86'},
  {kod:'HK',isim:'Hong Kong',bayrak:'🇭🇰',telKod:'+852'},
  {kod:'MO',isim:'Makao',bayrak:'🇲🇴',telKod:'+853'},
  {kod:'TW',isim:'Tayvan',bayrak:'🇹🇼',telKod:'+886'},
  {kod:'JP',isim:'Japonya',bayrak:'🇯🇵',telKod:'+81'},
  {kod:'KR',isim:'Güney Kore',bayrak:'🇰🇷',telKod:'+82'},
  {kod:'KP',isim:'Kuzey Kore',bayrak:'🇰🇵',telKod:'+850'},
  {kod:'MN',isim:'Moğolistan',bayrak:'🇲🇳',telKod:'+976'},
  {kod:'AU',isim:'Avustralya',bayrak:'🇦🇺',telKod:'+61'},
  {kod:'NZ',isim:'Yeni Zelanda',bayrak:'🇳🇿',telKod:'+64'},
  {kod:'FJ',isim:'Fiji',bayrak:'🇫🇯',telKod:'+679'},
  {kod:'PG',isim:'Papua Yeni Gine',bayrak:'🇵🇬',telKod:'+675'},
  {kod:'SB',isim:'Solomon Adaları',bayrak:'🇸🇧',telKod:'+677'},
  {kod:'VU',isim:'Vanuatu',bayrak:'🇻🇺',telKod:'+678'},
  {kod:'WS',isim:'Samoa',bayrak:'🇼🇸',telKod:'+685'},
  {kod:'TO',isim:'Tonga',bayrak:'🇹🇴',telKod:'+676'},
  {kod:'KI',isim:'Kiribati',bayrak:'🇰🇮',telKod:'+686'},
  {kod:'TV',isim:'Tuvalu',bayrak:'🇹🇻',telKod:'+688'},
  {kod:'NR',isim:'Nauru',bayrak:'🇳🇷',telKod:'+674'},
  {kod:'PW',isim:'Palau',bayrak:'🇵🇼',telKod:'+680'},
  {kod:'FM',isim:'Mikronezya',bayrak:'🇫🇲',telKod:'+691'},
  {kod:'MH',isim:'Marshall Adaları',bayrak:'🇲🇭',telKod:'+692'},
  {kod:'CA',isim:'Kanada',bayrak:'🇨🇦',telKod:'+1'},
  {kod:'MX',isim:'Meksika',bayrak:'🇲🇽',telKod:'+52'},
  {kod:'GT',isim:'Guatemala',bayrak:'🇬🇹',telKod:'+502'},
  {kod:'BZ',isim:'Belize',bayrak:'🇧🇿',telKod:'+501'},
  {kod:'HN',isim:'Honduras',bayrak:'🇭🇳',telKod:'+504'},
  {kod:'SV',isim:'El Salvador',bayrak:'🇸🇻',telKod:'+503'},
  {kod:'NI',isim:'Nikaragua',bayrak:'🇳🇮',telKod:'+505'},
  {kod:'CR',isim:'Kosta Rika',bayrak:'🇨🇷',telKod:'+506'},
  {kod:'PA',isim:'Panama',bayrak:'🇵🇦',telKod:'+507'},
  {kod:'CU',isim:'Küba',bayrak:'🇨🇺',telKod:'+53'},
  {kod:'JM',isim:'Jamaika',bayrak:'🇯🇲',telKod:'+1876'},
  {kod:'HT',isim:'Haiti',bayrak:'🇭🇹',telKod:'+509'},
  {kod:'DO',isim:'Dominik',bayrak:'🇩🇴',telKod:'+1809'},
  {kod:'PR',isim:'Porto Riko',bayrak:'🇵🇷',telKod:'+1787'},
  {kod:'TT',isim:'Trinidad Tobago',bayrak:'🇹🇹',telKod:'+1868'},
  {kod:'BB',isim:'Barbados',bayrak:'🇧🇧',telKod:'+1246'},
  {kod:'BS',isim:'Bahamalar',bayrak:'🇧🇸',telKod:'+1242'},
  {kod:'GD',isim:'Grenada',bayrak:'🇬🇩',telKod:'+1473'},
  {kod:'LC',isim:'Saint Lucia',bayrak:'🇱🇨',telKod:'+1758'},
  {kod:'VC',isim:'Saint Vincent',bayrak:'🇻🇨',telKod:'+1784'},
  {kod:'AG',isim:'Antigua',bayrak:'🇦🇬',telKod:'+1268'},
  {kod:'DM',isim:'Dominika',bayrak:'🇩🇲',telKod:'+1767'},
  {kod:'KN',isim:'Saint Kitts',bayrak:'🇰🇳',telKod:'+1869'},
  {kod:'BR',isim:'Brezilya',bayrak:'🇧🇷',telKod:'+55'},
  {kod:'AR',isim:'Arjantin',bayrak:'🇦🇷',telKod:'+54'},
  {kod:'CL',isim:'Şili',bayrak:'🇨🇱',telKod:'+56'},
  {kod:'PE',isim:'Peru',bayrak:'🇵🇪',telKod:'+51'},
  {kod:'CO',isim:'Kolombiya',bayrak:'🇨🇴',telKod:'+57'},
  {kod:'VE',isim:'Venezuela',bayrak:'🇻🇪',telKod:'+58'},
  {kod:'EC',isim:'Ekvador',bayrak:'🇪🇨',telKod:'+593'},
  {kod:'BO',isim:'Bolivya',bayrak:'🇧🇴',telKod:'+591'},
  {kod:'PY',isim:'Paraguay',bayrak:'🇵🇾',telKod:'+595'},
  {kod:'UY',isim:'Uruguay',bayrak:'🇺🇾',telKod:'+598'},
  {kod:'GY',isim:'Guyana',bayrak:'🇬🇾',telKod:'+592'},
  {kod:'SR',isim:'Surinam',bayrak:'🇸🇷',telKod:'+597'},
  {kod:'EG',isim:'Mısır',bayrak:'🇪🇬',telKod:'+20'},
  {kod:'LY',isim:'Libya',bayrak:'🇱🇾',telKod:'+218'},
  {kod:'TN',isim:'Tunus',bayrak:'🇹🇳',telKod:'+216'},
  {kod:'DZ',isim:'Cezayir',bayrak:'🇩🇿',telKod:'+213'},
  {kod:'MA',isim:'Fas',bayrak:'🇲🇦',telKod:'+212'},
  {kod:'MR',isim:'Moritanya',bayrak:'🇲🇷',telKod:'+222'},
  {kod:'SD',isim:'Sudan',bayrak:'🇸🇩',telKod:'+249'},
  {kod:'SS',isim:'Güney Sudan',bayrak:'🇸🇸',telKod:'+211'},
  {kod:'ET',isim:'Etiyopya',bayrak:'🇪🇹',telKod:'+251'},
  {kod:'ER',isim:'Eritre',bayrak:'🇪🇷',telKod:'+291'},
  {kod:'DJ',isim:'Cibuti',bayrak:'🇩🇯',telKod:'+253'},
  {kod:'SO',isim:'Somali',bayrak:'🇸🇴',telKod:'+252'},
  {kod:'KE',isim:'Kenya',bayrak:'🇰🇪',telKod:'+254'},
  {kod:'UG',isim:'Uganda',bayrak:'🇺🇬',telKod:'+256'},
  {kod:'TZ',isim:'Tanzanya',bayrak:'🇹🇿',telKod:'+255'},
  {kod:'RW',isim:'Ruanda',bayrak:'🇷🇼',telKod:'+250'},
  {kod:'BI',isim:'Burundi',bayrak:'🇧🇮',telKod:'+257'},
  {kod:'NG',isim:'Nijerya',bayrak:'🇳🇬',telKod:'+234'},
  {kod:'NE',isim:'Nijer',bayrak:'🇳🇪',telKod:'+227'},
  {kod:'TD',isim:'Çad',bayrak:'🇹🇩',telKod:'+235'},
  {kod:'CM',isim:'Kamerun',bayrak:'🇨🇲',telKod:'+237'},
  {kod:'CF',isim:'Orta Afrika',bayrak:'🇨🇫',telKod:'+236'},
  {kod:'GA',isim:'Gabon',bayrak:'🇬🇦',telKod:'+241'},
  {kod:'GQ',isim:'Ekvator Ginesi',bayrak:'🇬🇶',telKod:'+240'},
  {kod:'CG',isim:'Kongo Cum.',bayrak:'🇨🇬',telKod:'+242'},
  {kod:'CD',isim:'Kongo DC',bayrak:'🇨🇩',telKod:'+243'},
  {kod:'AO',isim:'Angola',bayrak:'🇦🇴',telKod:'+244'},
  {kod:'ZM',isim:'Zambiya',bayrak:'🇿🇲',telKod:'+260'},
  {kod:'MW',isim:'Malavi',bayrak:'🇲🇼',telKod:'+265'},
  {kod:'MZ',isim:'Mozambik',bayrak:'🇲🇿',telKod:'+258'},
  {kod:'ZW',isim:'Zimbabve',bayrak:'🇿🇼',telKod:'+263'},
  {kod:'BW',isim:'Botsvana',bayrak:'🇧🇼',telKod:'+267'},
  {kod:'NA',isim:'Namibya',bayrak:'🇳🇦',telKod:'+264'},
  {kod:'ZA',isim:'Güney Afrika',bayrak:'🇿🇦',telKod:'+27'},
  {kod:'LS',isim:'Lesoto',bayrak:'🇱🇸',telKod:'+266'},
  {kod:'SZ',isim:'Esvatini',bayrak:'🇸🇿',telKod:'+268'},
  {kod:'MG',isim:'Madagaskar',bayrak:'🇲🇬',telKod:'+261'},
  {kod:'MU',isim:'Mauritius',bayrak:'🇲🇺',telKod:'+230'},
  {kod:'SC',isim:'Seyşeller',bayrak:'🇸🇨',telKod:'+248'},
  {kod:'KM',isim:'Komorlar',bayrak:'🇰🇲',telKod:'+269'},
  {kod:'CV',isim:'Cabo Verde',bayrak:'🇨🇻',telKod:'+238'},
  {kod:'ST',isim:'Sao Tome',bayrak:'🇸🇹',telKod:'+239'},
  {kod:'SN',isim:'Senegal',bayrak:'🇸🇳',telKod:'+221'},
  {kod:'GM',isim:'Gambiya',bayrak:'🇬🇲',telKod:'+220'},
  {kod:'GN',isim:'Gine',bayrak:'🇬🇳',telKod:'+224'},
  {kod:'GW',isim:'Gine-Bissau',bayrak:'🇬🇼',telKod:'+245'},
  {kod:'SL',isim:'Sierra Leone',bayrak:'🇸🇱',telKod:'+232'},
  {kod:'LR',isim:'Liberya',bayrak:'🇱🇷',telKod:'+231'},
  {kod:'CI',isim:'Fildişi Sahili',bayrak:'🇨🇮',telKod:'+225'},
  {kod:'GH',isim:'Gana',bayrak:'🇬🇭',telKod:'+233'},
  {kod:'TG',isim:'Togo',bayrak:'🇹🇬',telKod:'+228'},
  {kod:'BJ',isim:'Benin',bayrak:'🇧🇯',telKod:'+229'},
  {kod:'BF',isim:'Burkina Faso',bayrak:'🇧🇫',telKod:'+226'},
  {kod:'ML',isim:'Mali',bayrak:'🇲🇱',telKod:'+223'},
];

export async function ulkeKoduTespitEt() {
  try {
    const r = await fetch('https://ipapi.co/json/', { signal: AbortSignal.timeout(3000) });
    if (r.ok) {
      const d = await r.json();
      if (d.country_code) {
        const b = ULKELER.find(u => u.kod === d.country_code);
        if (b) { console.log('[ULKE] IP\'den:', b.isim); return b; }
      }
    }
  } catch {}

  try {
    const r = await fetch('https://www.cloudflare.com/cdn-cgi/trace', { signal: AbortSignal.timeout(3000) });
    if (r.ok) {
      const t = await r.text();
      const m = t.match(/loc=([A-Z]{2})/);
      if (m?.[1]) {
        const b = ULKELER.find(u => u.kod === m[1]);
        if (b) { console.log('[ULKE] Cloudflare\'den:', b.isim); return b; }
      }
    }
  } catch {}

  try {
    const dil = navigator.language || '';
    if (dil.length >= 5) {
      const k = dil.split('-')[1]?.toUpperCase();
      const b = ULKELER.find(u => u.kod === k);
      if (b) { console.log('[ULKE] Dilden:', b.isim); return b; }
    }
  } catch {}

  console.log('[ULKE] Varsayılan: Almanya');
  return ULKELER[0];
}
